apiVersion: v1
kind: Pod
metadata:
  name: postsync-pod
  namespace: synctest
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
  labels:
    app.kubernetes.io/name: postsync-pod
spec:
  containers:
  - name: myapp-container
    image: registry.access.redhat.com/ubi8/ubi
    command: ['bash', '-c', 'sleep 3 ; echo Postsync']
    imagePullPolicy: Always
  restartPolicy: "Never"
